# coding=utf-8
from ..infra.sqlalchemy.ship import Ship
from ....shared.infra.sqlalchemy.base import Session, engine, Base

def execute():
    Base.metadata.create_all(engine)
    session = Session()


    slave_1 = Ship("Slave I", 1, 2.5)
    e_wing_fighter = Ship("E-Wing Starfighter", 2, 4.2)
    lady_luck = Ship("Lady Luck", 1, 2.2)
    jade_shadow = Ship("Slave I", 0.5, 2.5)
    hound_tooth = Ship("Hound Tooth", 1.5, 2.5)
    ig_2000 = Ship("IG-2000", 2, 2.5)
    sharp_spiral = Ship("Sharp Spiral", 0.6, 4.8)
    naboo_royal = Ship("Naboo Royal Starship", 1.8, 2.5)
    naboo_cruiser = Ship("Naboo Cruiser", 0.8, 2.4)
    n_1_starfighter = Ship("N-1 Starfighter", 1, 3.7)
    sith_infiltrator = Ship("Sith Infiltrator", 3, 3.7)
    droid_starfighter = Ship("Droid Starfighter", -1, 3.9)
    droid_control_ship = Ship("Droid Control Ship", 2, 0.4)
    wild_karrde = Ship("Wild Karrde", 1, 2.5)
    virago = Ship("Virago", 1, 4.2)
    inferno = Ship("Inferno", 0.7, 3.8)
    havoc = Ship("Havoc", 1.5, 2.7)
    solar_sailer = Ship("Solar Sailer", 1.5, 1)
    cloakshape_fighter = Ship("Cloakshape Fighter", 3.1, 2.4)
    jedi_Starfighter = Ship("Jedi Starfighter", 1, 5)
    jabitha = Ship("Jabitha", 0.5, 5.1)
    republic_assault_ship = Ship("Republic Assault Ship", 3.5, 2.4)
    yv_worldship = Ship("YV Worldship", 1.2, 2.5)
    yv_warship = Ship("YV Warship", 2.2, 2)
    yv_transport = Ship("YV Transport", -1, 1.5)

    session.add(slave_1)
    session.add(e_wing_fighter)
    session.add(lady_luck)
    session.add(jade_shadow)
    session.add(hound_tooth)
    session.add(ig_2000)
    session.add(sharp_spiral)
    session.add(naboo_royal)
    session.add(naboo_cruiser)
    session.add(n_1_starfighter)
    session.add(sith_infiltrator)
    session.add(droid_starfighter)
    session.add(droid_control_ship)
    session.add(wild_karrde)
    session.add(virago)
    session.add(inferno)
    session.add(havoc)
    session.add(solar_sailer)
    session.add(cloakshape_fighter)
    session.add(jedi_Starfighter)
    session.add(jabitha)
    session.add(republic_assault_ship)
    session.add(yv_worldship)
    session.add(yv_warship)
    session.add(yv_transport)



    session.commit()
    session.close()